export const FETCH_ERROR_USER = "[USERS] FETCH_ERROR";
export const FETCH_START_USER = "[USERS] FETCH_START";

export const FETCH_USER_SUCCESS = "[USERS] FETCH_USER_SUCCESS";
export const FETCH_USER_CART_SUCCESS = "[USERS] FETCH_USER_CART_SUCCESS";
export const LOGOUT_USER_SUCCESS = "[USERS] LOGOUT_USER_SUCCESS";
export const CLEAR_USERS_ERROR = "[USERS] CLEAR_USERS_ERROR";
export const FETCH_ORDERS_HISTORY_SUCCESS = "[USERS] FETCH_ORDERS_HISTORY_SUCCESS";
export const CLEAR_ORDERS_HISTORY = "[USERS] CLEAR_ORDERS_HISTORY";
export const SET_CURRENT_ORDER_SUCCESS = "[USERS] SET_CURRENT_ORDER_SUCCESS";
export const CLEAR_CURRENT_ORDER = "[USERS] CLEAR_CURRENT_ORDER";