export const FETCH_ERROR_USER: string = "[USERS] FETCH_ERROR";
export const FETCH_START_USER: string = "[USERS] FETCH_START";

export const FETCH_USER_SUCCESS: string = "[USERS] FETCH_USER_SUCCESS";
export const FETCH_USER_CART_SUCCESS: string = "[USERS] FETCH_USER_CART_SUCCESS";
export const LOGOUT_USER_SUCCESS: string = "[USERS] LOGOUT_USER_SUCCESS";
export const CLEAR_USERS_ERROR: string = "[USERS] CLEAR_USERS_ERROR";
export const FETCH_ORDERS_HISTORY_SUCCESS: string = "[USERS] FETCH_ORDERS_HISTORY_SUCCESS";
export const CLEAR_ORDERS_HISTORY: string = "[USERS] CLEAR_ORDERS_HISTORY";
export const SET_CURRENT_ORDER_SUCCESS: string = "[USERS] SET_CURRENT_ORDER_SUCCESS";
export const CLEAR_CURRENT_ORDER: string = "[USERS] CLEAR_CURRENT_ORDER";